import type { Customer } from "@/lib/customer-schema"

export const seedCustomers: Customer[] = [
  {
    id: "acme",
    name: "Acme Industries",
    region: "Global",
    plan: "Enterprise",
    status: "active",
    users: 890,
    storage: "64 TB",
    featureAdoption: 62,
  },
  {
    id: "wayne",
    name: "Wayne Enterprises",
    region: "Global",
    plan: "Enterprise",
    status: "active",
    users: 3200,
    storage: "256 TB",
    featureAdoption: 92,
  },
  {
    id: "globex",
    name: "Globex Pharmaceuticals",
    region: "US",
    plan: "Enterprise",
    status: "active",
    users: 2150,
    storage: "184 TB",
    featureAdoption: 85,
  },
  {
    id: "customer",
    name: "Customer Corp",
    region: "US-East",
    plan: "Enterprise",
    status: "active",
    users: 1240,
    storage: "92 TB",
    featureAdoption: 78,
  },
  {
    id: "initech",
    name: "Initech Software",
    region: "US-Central",
    plan: "Business",
    status: "active",
    users: 320,
    storage: "18 TB",
    featureAdoption: 45,
  },
  {
    id: "umbrella",
    name: "Umbrella Logistics",
    region: "APAC",
    plan: "Enterprise",
    status: "active",
    users: 1680,
    storage: "112 TB",
    featureAdoption: 71,
  },
  {
    id: "stark",
    name: "Stark Technologies",
    region: "US-East",
    plan: "Business",
    status: "active",
    users: 540,
    storage: "32 TB",
    featureAdoption: 88,
  },
  {
    id: "soylent",
    name: "Soylent Foods",
    region: "EU-Central",
    plan: "Starter",
    status: "trial",
    users: 410,
    storage: "22 TB",
    featureAdoption: 38,
  },
  {
    id: "hooli",
    name: "Hooli Cloud",
    region: "US-West",
    plan: "Business",
    status: "active",
    users: 980,
    storage: "78 TB",
    featureAdoption: 67,
  },
  {
    id: "pied-piper",
    name: "Pied Piper",
    region: "US-West",
    plan: "Starter",
    status: "active",
    users: 145,
    storage: "8 TB",
    featureAdoption: 52,
  },
  {
    id: "cyberdyne",
    name: "Cyberdyne Systems",
    region: "US-West",
    plan: "Business",
    status: "active",
    users: 720,
    storage: "48 TB",
    featureAdoption: 74,
  },
  {
    id: "tyrell",
    name: "Tyrell Corporation",
    region: "EU-West",
    plan: "Enterprise",
    status: "suspended",
    users: 1850,
    storage: "142 TB",
    featureAdoption: 81,
  },
]
