export const seedDevicesPage = {
  devices: [
    {
      type: "CTERA Portal",
      name: "Central Office US",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "25.5.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "up-to-date" as const,
      icon: "Server",
      category: "portals",
    },
    {
      type: "CTERA Edge Filer",
      name: "Operations UK",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "update-required" as const,
      icon: "HardDrive",
      category: "edge-filers",
    },
    {
      type: "CTERA Drive",
      name: "West HQ",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "20.4.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "update-critical" as const,
      icon: "Database",
      category: "cloud-drives",
    },
    {
      type: "CTERA Edge Filer",
      name: "Operations UK",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "update-critical" as const,
      icon: "HardDrive",
      category: "edge-filers",
    },
    {
      type: "CTERA Portal",
      name: "Central Office US",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "25.5.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "up-to-date" as const,
      icon: "Server",
      category: "portals",
    },
    {
      type: "CTERA Edge Filer",
      name: "Operations UK",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "update-required" as const,
      icon: "HardDrive",
      category: "edge-filers",
    },
    {
      type: "CTERA Drive",
      name: "West HQ",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "20.4.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "update-required" as const,
      icon: "Database",
      category: "cloud-drives",
    },
    {
      type: "CTERA Edge Filer",
      name: "Operations UK 2",
      description: "Primary US office managing operations and device activity",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      lastUpdate: "20-12-2025 14:16",
      status: "update-critical" as const,
      icon: "HardDrive",
      category: "edge-filers",
    },
  ],
}
