export const seedDownloads = {
  versionData: {
    "CTERA Portal": [
      {
        version: "8.3.3000",
        released: "2024-01-15",
        size: "245 MB",
        description: "Latest stable release with enhanced security features and performance improvements",
      },
      {
        version: "8.2.2800",
        released: "2024-01-01",
        size: "243 MB",
        description: "Bug fixes and minor enhancements",
      },
      {
        version: "8.2.2500",
        released: "2023-12-15",
        size: "241 MB",
        description: "Security patches and stability improvements",
      },
      {
        version: "8.2.2000",
        released: "2023-12-01",
        size: "240 MB",
        description: "Major release with new user interface and enhanced collaboration tools",
      },
    ],
    "CTERA Edge Filer": [
      {
        version: "7.11.5100",
        released: "2024-01-10",
        size: "156 MB",
        description: "Stable release with improved caching algorithms",
      },
      {
        version: "7.11.5000",
        released: "2023-12-20",
        size: "155 MB",
        description: "Performance improvements and bug fixes",
      },
      {
        version: "7.10.4900",
        released: "2023-12-05",
        size: "154 MB",
        description: "Security updates and stability enhancements",
      },
    ],
    "CTERA Drive - Windows": [
      {
        version: "5.2.1",
        released: "2024-01-12",
        size: "89 MB",
        description: "Latest stable release with improved sync and sharing performance",
        platform: "windows" as const,
      },
      {
        version: "5.2.0",
        released: "2023-12-28",
        size: "88 MB",
        description: "New features and performance improvements",
        platform: "windows" as const,
      },
      {
        version: "5.1.9",
        released: "2023-12-10",
        size: "87 MB",
        description: "Bug fixes and minor improvements",
        platform: "windows" as const,
      },
    ],
    "CTERA Drive - Mac": [
      {
        version: "5.2.1",
        released: "2024-01-12",
        size: "92 MB",
        description: "Latest stable release with improved sync and sharing performance",
        platform: "mac" as const,
      },
      {
        version: "5.2.0",
        released: "2023-12-28",
        size: "91 MB",
        description: "New features and performance improvements",
        platform: "mac" as const,
      },
      {
        version: "5.1.9",
        released: "2023-12-10",
        size: "90 MB",
        description: "Bug fixes and minor improvements",
        platform: "mac" as const,
      },
    ],
    "CTERA Drive Connect - Windows": [
      {
        version: "3.1.2",
        released: "2024-01-14",
        size: "45 MB",
        description: "Latest stable release with improved sync and sharing performance",
        platform: "windows" as const,
      },
      {
        version: "3.1.1",
        released: "2023-12-30",
        size: "44 MB",
        description: "Bug fixes and stability improvements",
        platform: "windows" as const,
      },
      {
        version: "3.1.0",
        released: "2023-12-15",
        size: "44 MB",
        description: "Major update with new UI and features",
        platform: "windows" as const,
      },
    ],
    "CTERA Drive Connect - Mac": [
      {
        version: "3.1.2",
        released: "2024-01-14",
        size: "48 MB",
        description: "Latest stable release with improved sync and sharing performance",
        platform: "mac" as const,
      },
      {
        version: "3.1.1",
        released: "2023-12-30",
        size: "47 MB",
        description: "Bug fixes and stability improvements",
        platform: "mac" as const,
      },
      {
        version: "3.1.0",
        released: "2023-12-15",
        size: "47 MB",
        description: "Major update with new UI and features",
        platform: "mac" as const,
      },
    ],
  },
  products: [
    {
      name: "CTERA Portal",
      icon: "Server",
      version: "8.3.300",
      released: "2024-01-15",
      size: "245 MB",
      progress: 100,
      progressLabel: "Up-to-Date",
      status: "success",
      description: "Latest stable release with enhanced security features and performance improvements",
      features: [] as string[],
    },
    {
      name: "CTERA Edge Filer",
      icon: "HardDrive",
      version: "7.11.5100",
      released: "2024-01-10",
      size: "156 MB",
      progress: 35,
      progressLabel: "2 updates required",
      status: "warning",
      description: "Stable release with improved caching algorithms",
      features: [] as string[],
    },
    {
      name: "CTERA Drive",
      icon: "Database",
      version: "5.2.1",
      released: "2024-01-12",
      size: "89 MB",
      progress: 35,
      progressLabel: "2 updates required",
      status: "warning",
      description: "Latest stable release with improved sync and sharing performance",
      features: [] as string[],
      hasPlatformSelector: true,
    },
    {
      name: "CTERA Drive Connect",
      iconUrl: "/images/drive-connect-icon.jpg",
      version: "3.1.2",
      released: "2024-01-14",
      size: "45 MB",
      progress: 15,
      progressLabel: "5 critical updates required",
      status: "error",
      description: "Latest stable release with improved sync and sharing performance",
      features: [] as string[],
      hasPlatformSelector: true,
    },
  ],
}
