export const seedFeatureAdoption = {
  featureAdoptionData: {
    infrastructure: [
      { name: "Application Server", description: "Application hosting services", enabled: true },
      { name: "Database Server", description: "Data storage systems", enabled: true },
      { name: "Database Replication Server", description: "Data redundancy and replication", enabled: true },
      { name: "Preview Server", description: "Preview and staging environments", enabled: false },
      { name: "DB Archiving", description: "Data archival systems", enabled: true },
      { name: "DB Replication", description: "Data redundancy", enabled: true },
      { name: "Backup to Bucket", description: "Cloud backup solutions", enabled: true },
    ],
    services: [
      { name: "Syslog", description: "System event logging", enabled: false },
      { name: "Edge Filer Syslog", description: "Edge-specific logging", enabled: true },
      { name: "KMS", description: "Key Management", enabled: true },
      { name: "Veeonis", description: "Data Security", enabled: false },
      { name: "SMTP", description: "Email delivery service", enabled: true },
      { name: "SMS", description: "Text messaging gateway", enabled: true },
      { name: "Backup Service", description: "Automated backup", enabled: true },
      { name: "Sync Service", description: "File synchronization", enabled: false },
      { name: "Audit Service", description: "Activity logging", enabled: true },
    ],
    tenantSettings: [
      { name: "Active Directory (AD)", description: "Domain integration", enabled: true },
      { name: "Access Based Presentation (ABP)", description: "Permission-based visibility", enabled: true },
      { name: "Single Sign On (SSO)", description: "Unified authentication", enabled: false },
      { name: "Super Tenant Users", description: "Superuser accounts", enabled: true },
      { name: "Skins", description: "Custom themes", enabled: false },
      { name: "Configuration Templates", description: "Setup templates", enabled: true },
      { name: "Button Generator", description: "Brand color schemes", enabled: true },
      { name: "Email Templates", description: "Notification customization", enabled: false },
      { name: "Teams Integration", description: "Microsoft Teams connectivity", enabled: true },
      { name: "Global File Lock (GFL)", description: "Concurrent access control", enabled: true },
      { name: "Office Online", description: "Web-based editing", enabled: true },
      { name: "Cloud Drive Policy", description: "Access permissions", enabled: false },
      { name: "Zones Enabled", description: "Multi-zone deployment", enabled: true },
    ],
    globalSettings: [
      { name: "iFrame Enabled", description: "Web embedding capability", enabled: true },
      { name: "Global AD", description: "Active Directory integration", enabled: true },
      { name: "Global Admin SSO", description: "Single sign on for admins", enabled: true },
      { name: "Global Admin Access Control", description: "Role-based permissions", enabled: true },
      { name: "Firmware Repository", description: "Internal update management", enabled: true },
      { name: "Skins", description: "UI customization themes", enabled: false },
      { name: "Roles - Super User", description: "Administrative privileges", enabled: true },
      { name: "Custom Log Based Alerts", description: "Monitoring notifications", enabled: true },
    ],
  },
  prdData: [
    {
      category: "Infrastructure",
      name: "Application Server",
      description: "Application hosting services",
      purpose: "Hosts the CTERA portal application layer and serves web requests to end users.",
      requirement: "Must be running and reachable before any portal functionality is available.",
      enabled: true,
    },
    {
      category: "Infrastructure",
      name: "Database Server",
      description: "Primary data storage system",
      purpose: "Stores all persistent portal data including user records, policies, and file metadata.",
      requirement: "Required for all read/write operations. Must be highly available.",
      enabled: true,
    },
    {
      category: "Infrastructure",
      name: "Database Replication Server",
      description: "Data redundancy and replication",
      purpose: "Maintains a synchronized replica of the primary database for failover and load distribution.",
      requirement: "Recommended for production deployments with more than 50 users.",
      enabled: true,
    },
    {
      category: "Infrastructure",
      name: "Preview Server",
      description: "Preview and staging environments",
      purpose: "Generates file previews (thumbnails, document previews) for the portal UI.",
      requirement: "Optional. Enhances user experience but is not required for core operations.",
      enabled: false,
    },
    {
      category: "Infrastructure",
      name: "DB Archiving",
      description: "Data archival systems",
      purpose: "Moves aged or infrequently accessed database records to cold storage to reduce primary DB load.",
      requirement: "Recommended for deployments older than 12 months with high data volume.",
      enabled: true,
    },
    {
      category: "Infrastructure",
      name: "DB Replication",
      description: "Data redundancy",
      purpose: "Enables replication of database changes across nodes for disaster recovery.",
      requirement: "Required for multi-site deployments and high-availability configurations.",
      enabled: true,
    },
    {
      category: "Infrastructure",
      name: "Backup to Bucket",
      description: "Cloud backup solutions",
      purpose: "Exports portal configuration and data backups to an object storage bucket (e.g. S3).",
      requirement: "Required for disaster recovery compliance. Must be configured with valid bucket credentials.",
      enabled: true,
    },
    {
      category: "Services",
      name: "Syslog",
      description: "System event logging",
      purpose: "Forwards portal system events to an external syslog server for centralized log management.",
      requirement: "Optional. Required for SOC/SIEM integrations.",
      enabled: false,
    },
    {
      category: "Services",
      name: "Edge Filer Syslog",
      description: "Edge-specific logging",
      purpose: "Sends edge filer device logs to a remote syslog endpoint for monitoring and auditing.",
      requirement: "Optional. Recommended for environments with managed edge filer fleets.",
      enabled: true,
    },
    {
      category: "Services",
      name: "KMS",
      description: "Key Management Service",
      purpose: "Integrates with an external Key Management Service to manage encryption keys for data at rest.",
      requirement: "Required for deployments with data encryption compliance requirements.",
      enabled: true,
    },
    {
      category: "Services",
      name: "Veeonis",
      description: "Data Security integration",
      purpose: "Connects CTERA with the Veeam/Veeonis data protection platform for backup orchestration.",
      requirement: "Optional. Required only if using Veeam as the backup provider.",
      enabled: false,
    },
    {
      category: "Services",
      name: "SMTP",
      description: "Email delivery service",
      purpose: "Configures outbound email for notifications, alerts, password resets, and user invitations.",
      requirement: "Required for all user-facing email communication.",
      enabled: true,
    },
    {
      category: "Services",
      name: "SMS",
      description: "Text messaging gateway",
      purpose: "Enables SMS-based notifications and two-factor authentication for portal users.",
      requirement: "Optional. Required if SMS-based MFA is enabled.",
      enabled: true,
    },
    {
      category: "Services",
      name: "Backup Service",
      description: "Automated backup",
      purpose: "Runs scheduled automated backups of portal data and configuration.",
      requirement: "Required for production environments. Must be tested at least quarterly.",
      enabled: true,
    },
    {
      category: "Services",
      name: "Sync Service",
      description: "File synchronization",
      purpose: "Manages real-time file sync between cloud and edge filer devices.",
      requirement: "Required if Cloud Drive or edge sync features are in use.",
      enabled: false,
    },
    {
      category: "Services",
      name: "Audit Service",
      description: "Activity logging",
      purpose: "Records all user and admin activity within the portal for compliance and forensics.",
      requirement: "Recommended for all deployments. Required for HIPAA/ISO compliance.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Active Directory (AD)",
      description: "Domain integration",
      purpose: "Integrates portal authentication with the customer's Active Directory for SSO and user provisioning.",
      requirement: "Required for enterprise deployments using Windows domain accounts.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Access Based Presentation (ABP)",
      description: "Permission-based visibility",
      purpose: "Hides files and folders from users who do not have access permissions.",
      requirement: "Optional. Recommended for multi-tenant and shared-drive configurations.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Single Sign On (SSO)",
      description: "Unified authentication",
      purpose: "Enables SAML or OIDC-based SSO so users log in via their identity provider.",
      requirement: "Optional. Required when integrating with Okta, Azure AD, or similar IdPs.",
      enabled: false,
    },
    {
      category: "Tenant Settings",
      name: "Super Tenant Users",
      description: "Superuser accounts",
      purpose: "Allows designated super-tenant administrators to manage multiple tenant environments.",
      requirement: "Required for MSP or multi-tenant management scenarios.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Skins",
      description: "Custom UI themes",
      purpose: "Allows white-labeling of the portal UI with custom logos, colors, and branding assets.",
      requirement: "Optional. Used by resellers and MSPs requiring branded portals.",
      enabled: false,
    },
    {
      category: "Tenant Settings",
      name: "Configuration Templates",
      description: "Setup templates",
      purpose: "Provides predefined configuration templates for rapid tenant provisioning.",
      requirement: "Optional. Recommended for large-scale deployments with consistent configurations.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Button Generator",
      description: "Brand color schemes",
      purpose: "Generates themed UI button assets matching the tenant's brand palette.",
      requirement: "Optional. Used alongside Skins for full white-labeling.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Email Templates",
      description: "Notification customization",
      purpose: "Allows customization of all outbound email templates with tenant branding and copy.",
      requirement: "Optional. Recommended for tenants with specific brand communication standards.",
      enabled: false,
    },
    {
      category: "Tenant Settings",
      name: "Teams Integration",
      description: "Microsoft Teams connectivity",
      purpose: "Enables file sharing and collaboration actions directly within Microsoft Teams channels.",
      requirement: "Optional. Required for organizations using Teams as the primary collaboration tool.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Global File Lock (GFL)",
      description: "Concurrent access control",
      purpose: "Prevents simultaneous edits to the same file by locking it when one user opens it.",
      requirement: "Recommended for any deployment with shared documents and concurrent users.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Office Online",
      description: "Web-based editing",
      purpose: "Integrates Microsoft Office Online (WOPI) for browser-based document editing.",
      requirement: "Optional. Requires a valid Office Online Server or Microsoft 365 license.",
      enabled: true,
    },
    {
      category: "Tenant Settings",
      name: "Cloud Drive Policy",
      description: "Access permissions",
      purpose: "Defines granular policies controlling what actions users can perform in Cloud Drive.",
      requirement: "Required when fine-grained access control for Drive users is needed.",
      enabled: false,
    },
    {
      category: "Tenant Settings",
      name: "Zones Enabled",
      description: "Multi-zone deployment",
      purpose: "Partitions the portal into geographic or logical zones for data residency and performance.",
      requirement: "Required for deployments with data residency requirements or multi-region infrastructure.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "iFrame Enabled",
      description: "Web embedding capability",
      purpose: "Allows the portal UI to be embedded inside an iFrame within external web applications.",
      requirement: "Optional. Required for portal integrations embedded in third-party dashboards.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "Global AD",
      description: "Global Active Directory integration",
      purpose: "Extends Active Directory integration across all tenants at the global admin level.",
      requirement: "Required for centralized identity management across multiple tenants.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "Global Admin SSO",
      description: "Single sign on for admins",
      purpose: "Enables SSO authentication specifically for global administrators managing the platform.",
      requirement: "Recommended for all deployments. Required if admin accounts are managed via an IdP.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "Global Admin Access Control",
      description: "Role-based permissions",
      purpose: "Defines and enforces role-based access controls for global administrators.",
      requirement: "Required for compliance with least-privilege security principles.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "Firmware Repository",
      description: "Internal update management",
      purpose: "Hosts firmware packages internally so edge filers can update from a local repository.",
      requirement: "Required for air-gapped or restricted-network deployments.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "Skins",
      description: "Global UI customization themes",
      purpose: "Applies white-label theming globally across all tenants in the deployment.",
      requirement: "Optional. Used by platform operators managing multiple branded tenants.",
      enabled: false,
    },
    {
      category: "Global Settings",
      name: "Roles - Super User",
      description: "Administrative privileges",
      purpose: "Grants super-user role capabilities to designated platform administrators.",
      requirement: "Required for break-glass admin access and platform-level configuration changes.",
      enabled: true,
    },
    {
      category: "Global Settings",
      name: "Custom Log Based Alerts",
      description: "Monitoring notifications",
      purpose: "Sends alerts when specific log patterns are detected, enabling proactive monitoring.",
      requirement: "Optional. Recommended for production environments with SLA requirements.",
      enabled: true,
    },
  ],
  categorySummary: [
    { label: "Infrastructure", total: 7, enabled: 6, disabled: 1 },
    { label: "Services", total: 9, enabled: 6, disabled: 3 },
    { label: "Tenant Settings", total: 13, enabled: 9, disabled: 4 },
    { label: "Global Settings", total: 8, enabled: 7, disabled: 1 },
  ],
}
