export const seedPortal = {
  devices: [
    {
      id: 1,
      name: "Central Office US",
      type: "CTERA Portal",
      location: "US",
      latestVersion: "25.5.19.439",
      installedVersion: "25.5.19.439",
      status: "up-to-date" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 39.8,
      lng: -98.5,
    },
    {
      id: 2,
      name: "Operations UK",
      type: "CTERA Edge Filer",
      location: "UK",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      status: "update-critical" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 55.3,
      lng: -3.4,
    },
    {
      id: 3,
      name: "West HQ",
      type: "CTERA Drive",
      location: "US West",
      latestVersion: "25.5.19.439",
      installedVersion: "20.4.19.439",
      status: "update-required" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 37.8,
      lng: -122.4,
    },
    {
      id: 4,
      name: "Operations UK 2",
      type: "CTERA Edge Filer",
      location: "UK",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      status: "update-critical" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 51.5,
      lng: -0.1,
    },
    {
      id: 5,
      name: "Central Office US",
      type: "CTERA Portal",
      location: "US Central",
      latestVersion: "25.5.19.439",
      installedVersion: "25.5.19.439",
      status: "up-to-date" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 41.8,
      lng: -87.6,
    },
    {
      id: 6,
      name: "Operations UK",
      type: "CTERA Edge Filer",
      location: "UK",
      latestVersion: "25.5.19.439",
      installedVersion: "21.5.19.439",
      status: "update-required" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 53.4,
      lng: -2.2,
    },
    {
      id: 7,
      name: "West HQ",
      type: "CTERA Drive",
      location: "Asia",
      latestVersion: "25.5.19.439",
      installedVersion: "20.4.19.439",
      status: "update-required" as const,
      lastUpdate: "20-12-2025 14:16",
      description: "Primary US office managing operations and device activity",
      lat: 35.6,
      lng: 139.6,
    },
  ],
  latestVersions: [
    { name: "Portal", deviceCount: 2, icon: "📱", status: "up-to-date" as const },
    { name: "CTERA Edge Filer", deviceCount: 4, icon: "🖥️", status: "update-required" as const },
    { name: "CTERA Drive", deviceCount: 2, icon: "💾", status: "update-required" as const },
    { name: "CTERA Mobile App", deviceCount: 0, icon: "📱", status: "up-to-date" as const },
  ],
  recommendations: [
    {
      title: "Enable Database Replication",
      priority: "High",
      category: "Security",
      description: "Adding database replication provides critical resilience.",
      benefits: ["High availability with automatic failover", "Disaster recovery protection", "Zero data loss guarantee"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      title: "Upgrade Outdated Edge Filers",
      priority: "High",
      category: "Security",
      description: "23 Edge Filer devices are running v7.0.1 (outdated). Upgrading to v7.0.3 will provide:",
      benefits: [
        "Improved security with latest patches",
        "15% performance enhancement",
        "New ransomware protection features",
      ],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      title: "Expand Storage Capacity",
      priority: "High",
      category: "Performance",
      description: "Your storage is at 85% capacity. Expanding now will prevent service disruptions:",
      benefits: ["Avoid automatic quota enforcement", "Support business growth", "Improve backup retention"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      title: "Renew License Early",
      priority: "Medium",
      category: "Licensing",
      description: "Your license expires in 45 days. Renewing early ensures:",
      benefits: ["Uninterrupted service access", "Lock in current pricing", "Qualify for early renewal discount"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      title: "Enable Preview Server",
      priority: "Low",
      category: "Testing",
      description: "Deploy a preview server to safely test changes before production:",
      benefits: ["Zero-downtime deployments", "Test configurations safely", "Reduce production incidents by 80%"],
      image: "/placeholder.svg?height=200&width=400",
    },
    {
      title: "Add CTERA Storage Class",
      priority: "Low",
      category: "Optimization",
      description: "Add CTERA Storage Class for geo-distributed, more efficient storage management:",
      benefits: [
        "Optimize data placement across regions",
        "Reduce latency for global users",
        "Lower storage and bandwidth costs",
      ],
      image: "/placeholder.svg?height=200&width=400",
    },
  ],
  featureAdoptionData: {
    infrastructure: [
      { name: "Application Server", description: "Application hosting services", enabled: true },
      { name: "Database Server", description: "Data storage systems", enabled: true },
      { name: "Database Replication Server", description: "Data redundancy and replication", enabled: true },
      { name: "Preview Server", description: "Preview and staging environments", enabled: false },
      { name: "DB Archiving", description: "Data archival systems", enabled: true },
      { name: "DB Replication", description: "Data redundancy", enabled: true },
      { name: "Backup to Bucket", description: "Cloud backup solutions", enabled: true },
    ],
    services: [
      { name: "Syslog", description: "System event logging", enabled: false },
      { name: "Edge Filer Syslog", description: "Edge-specific logging", enabled: true },
      { name: "KMS", description: "Key Management", enabled: true },
      { name: "Veeonis", description: "Data Security", enabled: false },
      { name: "SMTP", description: "Email delivery service", enabled: true },
      { name: "SMS", description: "Text messaging gateway", enabled: true },
      { name: "Backup Service", description: "Automated backup", enabled: true },
      { name: "Sync Service", description: "File synchronization", enabled: false },
      { name: "Audit Service", description: "Activity logging", enabled: true },
    ],
    tenantSettings: [
      { name: "Active Directory (AD)", description: "Domain integration", enabled: true },
      { name: "Access Based Presentation (ABP)", description: "Permission-based visibility", enabled: true },
      { name: "Single Sign On (SSO)", description: "Unified authentication", enabled: false },
      { name: "Super Tenant Users", description: "Superuser accounts", enabled: true },
      { name: "Skins", description: "Custom themes", enabled: false },
      { name: "Configuration Templates", description: "Setup templates", enabled: true },
      { name: "Button Generator", description: "Brand color schemes", enabled: true },
      { name: "Email Templates", description: "Notification customization", enabled: false },
      { name: "Teams Integration", description: "Microsoft Teams connectivity", enabled: true },
      { name: "Global File Lock (GFL)", description: "Concurrent access control", enabled: true },
      { name: "Office Online", description: "Web-based editing", enabled: true },
      { name: "Cloud Drive Policy", description: "Access permissions", enabled: false },
      { name: "Zones Enabled", description: "Multi-zone deployment", enabled: true },
    ],
    globalSettings: [
      { name: "iFrame Enabled", description: "Web embedding capability", enabled: true },
      { name: "Global AD", description: "Active Directory integration", enabled: true },
      { name: "Global Admin SSO", description: "Single sign on for admins", enabled: true },
      { name: "Global Admin Access Control", description: "Role-based permissions", enabled: true },
      { name: "Firmware Repository", description: "Internal update management", enabled: true },
      { name: "Skins", description: "UI customization themes", enabled: false },
      { name: "Roles - Super User", description: "Administrative privileges", enabled: true },
      { name: "Custom Log Based Alerts", description: "Monitoring notifications", enabled: true },
    ],
  },
}
