import type { Tenant } from "../../hub-schema"

export const seedTenants: Tenant[] = [
  {
    id: "customer",
    name: "Customer Corp",
    domain: "customer.ctera.com",
    region: "US-East",
    users: 1240,
    storage: "92 TB",
    featureAdoption: 78,
    status: "active",
    plan: "Enterprise",
  },
  {
    id: "acme",
    name: "Acme Industries",
    domain: "acme.ctera.com",
    region: "EU-West",
    users: 890,
    storage: "64 TB",
    featureAdoption: 62,
    status: "active",
    plan: "Enterprise",
  },
  {
    id: "globex",
    name: "Globex Pharmaceuticals",
    domain: "globex.ctera.com",
    region: "US-West",
    users: 2150,
    storage: "184 TB",
    featureAdoption: 85,
    status: "active",
    plan: "Enterprise",
  },
  {
    id: "initech",
    name: "Initech Software",
    domain: "initech.ctera.com",
    region: "US-Central",
    users: 320,
    storage: "18 TB",
    featureAdoption: 45,
    status: "active",
    plan: "Business",
  },
  {
    id: "umbrella",
    name: "Umbrella Logistics",
    domain: "umbrella.ctera.com",
    region: "APAC",
    users: 1680,
    storage: "112 TB",
    featureAdoption: 71,
    status: "active",
    plan: "Enterprise",
  },
  {
    id: "stark",
    name: "Stark Technologies",
    domain: "stark.ctera.com",
    region: "US-East",
    users: 540,
    storage: "32 TB",
    featureAdoption: 88,
    status: "active",
    plan: "Business",
  },
  {
    id: "wayne",
    name: "Wayne Enterprises",
    domain: "wayne.ctera.com",
    region: "US-East",
    users: 3200,
    storage: "256 TB",
    featureAdoption: 92,
    status: "active",
    plan: "Enterprise",
  },
  {
    id: "soylent",
    name: "Soylent Foods",
    domain: "soylent.ctera.com",
    region: "EU-Central",
    users: 410,
    storage: "22 TB",
    featureAdoption: 38,
    status: "trial",
    plan: "Starter",
  },
  {
    id: "hooli",
    name: "Hooli Cloud",
    domain: "hooli.ctera.com",
    region: "US-West",
    users: 980,
    storage: "78 TB",
    featureAdoption: 67,
    status: "active",
    plan: "Business",
  },
  {
    id: "pied-piper",
    name: "Pied Piper",
    domain: "piedpiper.ctera.com",
    region: "US-West",
    users: 145,
    storage: "8 TB",
    featureAdoption: 52,
    status: "active",
    plan: "Starter",
  },
  {
    id: "cyberdyne",
    name: "Cyberdyne Systems",
    domain: "cyberdyne.ctera.com",
    region: "US-West",
    users: 720,
    storage: "48 TB",
    featureAdoption: 74,
    status: "active",
    plan: "Business",
  },
  {
    id: "tyrell",
    name: "Tyrell Corporation",
    domain: "tyrell.ctera.com",
    region: "EU-West",
    users: 1850,
    storage: "142 TB",
    featureAdoption: 81,
    status: "suspended",
    plan: "Enterprise",
  },
]
